default: &default
  adapter: mysql2
  encoding: utf8mb4
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "mdbroot" } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>

development:
  primary: &primary_development
    <<: *default
    database: amiverse_development
  cache:
    <<: *primary_development
    database: amiverse_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: amiverse_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: amiverse_development_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: amiverse_test

production:
  primary: &primary_production
    <<: *default
    database: amiverse_production
  cache:
    <<: *primary_production
    database: amiverse_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: amiverse_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: amiverse_production_cable
    migrations_paths: db/cable_migrate
